[project]
name = "preflight"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "rich>=14.0.0",
    "streamlit>=1.44.1",
    "textual>=3.1.1",
    "typer>=0.15.2",
    "watchdog>=6.0.0",
]
